# Default values for helmChart.
# Declare variables to be passed into your templates.

# deployment.yaml values

appName: django-app
replicaCount: 2
image:
  # ECR repository
  repository: 908694979971.dkr.ecr.us-east-1.amazonaws.com/myrepo
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest
  containerPort: 8000

service:
  serviceName: django-app-service
  portName: django-app-service-port
  port: 8000
  protocol: TCP

# ingress.yaml values

ingress:
  ingressName: django-app-ingress
  enabled: true
  rules:
    path: /
    pathType: Prefix

# hpa.yaml values HorizontalPodAutoscaler

autoscaling:
  autoscalingName: django-app-hpa
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# custom resources

resources: {}
  # If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
