version: '3'
services:
  web:
    env_file:
      - ./djangoApp/.env
    build: .
    container_name: djangoApp
    networks: 
      - django
    ports:
      - 8000:8000
    volumes:
      - django:/app
networks:
  django:
    name: django-net
volumes:
  django:
    name: django-data
