# Generated by Django 4.2.4 on 2023-08-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listingIPApp', '0003_alter_ipaddresses_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddresses',
            name='ip_address',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterUniqueTogether(
            name='ipaddresses',
            unique_together={('ip_address', 'date_added')},
        ),
    ]
