# Generated by Django 4.2.4 on 2023-08-21 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listingIPApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IPAdresses',
            new_name='IPAddresses',
        ),
    ]
