# Generated by Django 4.2.4 on 2023-08-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listingIPApp', '0004_alter_ipaddresses_ip_address_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ipaddresses',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='ipaddresses',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ipaddresses',
            name='ip_address',
            field=models.GenericIPAddressField(unique=True),
        ),
    ]
