apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.serviceName }}
  labels:
    app: {{ .Values.appName }}
spec:
  type: LoadBalancer
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  ports:
    - name: {{ .Values.service.portName }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.image.containerPort }}
      protocol: {{ .Values.service.protocol }}